### ISSUE TITLE
Dataview Question

### ISSUE THREAD

**Issue by anvimea** [Elaws/script_videogames_quickAdd#1]
Thanks for posting this! Out of curiosity would you also mind adding the code for the dataview render with all your games? The one shown at the end of the demonstration.

**Comment by Elaws** [comment]
Hello @anvimea, 

Please find the [updated Readme](https://github.com/Elaws/script_videogames_quickAdd/blob/master/README.md#dataview-rendering) showing the dataview query used ;)

**Comment by anvimea** [comment]
Thanks!
